---
- name: Install Elk
  hosts: elk
  become: true
  tasks:
  - name: install packages
    sysctl:
        name: sysctl.conf
        value: 262144
        state: present
        run: echo "vm size set"

  - name: docker.io
    apt:
      force_apt_get: yes
      update_cache: yes
      name: docker.io
      state: present
      run: echo "docker.io done"

  - name: Install pip3
    apt:
      force_apt_get: yes
      name: python3-pip
      state: present
      run: echo "pip3 installed"

  - name: Install Docker python module
    pip:
      name: docker
      state: present
      run: echo "docker python module done"

  - name: download and launch a docker web container
    docker_container:
      name: dvwa
      image: cyberxsecurity/dvwa
      state: started
      published_ports: 80:80
      run: echo "launched docker web container"

  - name: Enable docker service
    systemd:
      name: docker
      enabled: yes
      run: echo "enabled docker service"
